title: Meetup No. 16: The Autonomous Vehicle Corridor
author: Civic Tech YVR community
github_username: CivicTechVancouver
timezone: America/Vancouver
permalink: /:title.html

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
